# Generated by Django 4.1.5 on 2023-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_payed',
            field=models.BooleanField(default=True),
        ),
    ]
