# Generated by Django 4.1.5 on 2023-02-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_appointmentuser_booking_bookinuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_payed',
        ),
    ]
