# Generated by Django 4.1.5 on 2023-02-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_caravan_owner_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='carvan_status',
            field=models.BooleanField(default=False),
        ),
    ]
